// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkZ1RBkDIrR6990Qz7NRbKUmEaQOaxU0I',
    appId: '1:522585343125:web:cac378d3808131b60b879c',
    messagingSenderId: '522585343125',
    projectId: 'events-ddd01',
    authDomain: 'events-ddd01.firebaseapp.com',
    storageBucket: 'events-ddd01.appspot.com',
    measurementId: 'G-RZH4FFEXMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-GcGulZ_6FdLj_4JO--emq7wuh2O020w',
    appId: '1:522585343125:android:7f779c7f95c838a70b879c',
    messagingSenderId: '522585343125',
    projectId: 'events-ddd01',
    storageBucket: 'events-ddd01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2clAdebR_RPM001R5o2R4drixXj4WY4o',
    appId: '1:522585343125:ios:a70e5747e83882790b879c',
    messagingSenderId: '522585343125',
    projectId: 'events-ddd01',
    storageBucket: 'events-ddd01.appspot.com',
    androidClientId: '522585343125-is6t7ubdqhes423a34etftkhmvv3a8uu.apps.googleusercontent.com',
    iosClientId: '522585343125-dmbvctlifiu2knfivevdh07ppr6qeckq.apps.googleusercontent.com',
    iosBundleId: 'com.example.communityTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2clAdebR_RPM001R5o2R4drixXj4WY4o',
    appId: '1:522585343125:ios:5b8981bdb01d14660b879c',
    messagingSenderId: '522585343125',
    projectId: 'events-ddd01',
    storageBucket: 'events-ddd01.appspot.com',
    androidClientId: '522585343125-is6t7ubdqhes423a34etftkhmvv3a8uu.apps.googleusercontent.com',
    iosClientId: '522585343125-20ac58mina3p8q7jnnb8k89ug11omaml.apps.googleusercontent.com',
    iosBundleId: 'com.example.communityTest.RunnerTests',
  );
}
