// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkZ1RBkDIrR6990Qz7NRbKUmEaQOaxU0I',
    appId: '1:522585343125:web:cac378d3808131b60b879c',
    messagingSenderId: '522585343125',
    projectId: 'events-ddd01',
    authDomain: 'events-ddd01.firebaseapp.com',
    storageBucket: 'events-ddd01.appspot.com',
    measurementId: 'G-RZH4FFEXMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-GcGulZ_6FdLj_4JO--emq7wuh2O020w',
    appId: '1:522585343125:android:e3ecf562abac419d0b879c',
    messagingSenderId: '522585343125',
    projectId: 'events-ddd01',
    storageBucket: 'events-ddd01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2clAdebR_RPM001R5o2R4drixXj4WY4o',
    appId: '1:522585343125:ios:5ad4c7bdd93e89140b879c',
    messagingSenderId: '522585343125',
    projectId: 'events-ddd01',
    storageBucket: 'events-ddd01.appspot.com',
    iosClientId: '522585343125-4bd6jive47vmne1kgfbtc3mjrdk8pia0.apps.googleusercontent.com',
    iosBundleId: 'com.example.test4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2clAdebR_RPM001R5o2R4drixXj4WY4o',
    appId: '1:522585343125:ios:984edd631aed94ed0b879c',
    messagingSenderId: '522585343125',
    projectId: 'events-ddd01',
    storageBucket: 'events-ddd01.appspot.com',
    iosClientId: '522585343125-dcauv7iq38rqafpiem0ai8m6sgdhn7pi.apps.googleusercontent.com',
    iosBundleId: 'com.example.test4.RunnerTests',
  );
}
